apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackdemo-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stackdemo-ui
  template:
    metadata:
      labels:
        app: stackdemo-ui
    spec:
      containers:
      - image: abhishekganji27/stackdemo:20
        name: stackdemo-ui
        ports:
        - containerPort: 8000
